# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo 'Below is securefile'
  displayName: 'Run the script'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'ubuntuvmkey.pem'

- script: cat $(ubuntuvmkey.pem)